[build]
  command = "ng build --prod"
  publish = "dist/my-app"

[[plugins]]
  package = "netlify-plugin-headers"

[[plugins]]
  package = "netlify-plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-redirects"

[[plugins]]
  package = "netlify-plugin-cleanup"

[[plugins]]
  package = "netlify-plugin-json-server"
  command = "json-server db.json --routes routes.json --middlewares middlewares.json"
  port = 3000

 [plugins.inputs]
    origin = "config"
