[build]
  command = "ng build --prod"
  publish = "dist/my-app"



[[plugins]]
  package = "netlify-plugin-json-server"
  command = "json-server db.json --routes routes.json --middlewares middlewares.json"
  port = 3000
